GET http://localhost:5104/games

###
GET http://localhost:5104/games/7

###
POST http://localhost:5104/games
Content-Type: application/json

{
    "name" : "Minecraft",
    "genre": "Kids And Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}