GET http://localhost:5104/games

###
GET http://localhost:5104/games/2

###
POST http://localhost:5104/games
Content-Type: application/json

{
    "name": "Donkey Kong",
    "genreid": 1,
    "price": 19.99,
    "releaseDate": "2011-12-11"
}

###
PUT http://localhost:5104/games/2
Content-Type: application/json

{
    "name": "Donkey Kong 2",
    "genreid": 1,
    "price": 19.99,
    "releaseDate": "2014-12-11"
}

###
DELETE http://localhost:5104/games/2